import type { Transaction } from "@/types/finance";

export const mockTransactions: Transaction[] = [
  {
    id: "txn-001",
    description: "Nómina Mayo",
    amount: 32000,
    type: "income",
    category: "salary",
    date: "2025-05-15",
    accountId: "acc-003",
    currency: "MXN",
  },
  {
    id: "txn-002",
    description: "Renta departamento",
    amount: 9500,
    type: "expense",
    category: "housing",
    date: "2025-05-01",
    accountId: "acc-001",
    currency: "MXN",
  },
  {
    id: "txn-003",
    description: "Uber Eats",
    amount: 285,
    type: "expense",
    category: "food",
    date: "2025-05-26",
    accountId: "acc-001",
    currency: "MXN",
  },
  {
    id: "txn-004",
    description: "Netflix",
    amount: 219,
    type: "expense",
    category: "entertainment",
    date: "2025-05-18",
    accountId: "acc-001",
    currency: "MXN",
  },
  {
    id: "txn-005",
    description: "Gasolinera",
    amount: 800,
    type: "expense",
    category: "transport",
    date: "2025-05-24",
    accountId: "acc-001",
    currency: "MXN",
  },
  {
    id: "txn-006",
    description: "Supermercado Walmart",
    amount: 1350,
    type: "expense",
    category: "food",
    date: "2025-05-22",
    accountId: "acc-001",
    currency: "MXN",
  },
  {
    id: "txn-007",
    description: "Freelance diseño",
    amount: 5000,
    type: "income",
    category: "other",
    date: "2025-05-20",
    accountId: "acc-001",
    currency: "MXN",
  },
  {
    id: "txn-008",
    description: "Transferencia a Nu",
    amount: 10000,
    type: "transfer",
    category: "transfer",
    date: "2025-05-16",
    accountId: "acc-003",
    currency: "MXN",
  },
  {
    id: "txn-009",
    description: "Gimnasio",
    amount: 699,
    type: "expense",
    category: "health",
    date: "2025-05-10",
    accountId: "acc-001",
    currency: "MXN",
  },
  {
    id: "txn-010",
    description: "Amazon — audífonos",
    amount: 1890,
    type: "expense",
    category: "shopping",
    date: "2025-05-08",
    accountId: "acc-001",
    currency: "MXN",
  },
];
